package com.bat.promotion.service.common;

/**
 * @author bat(b2b_bat @ 163.com)
 * @date 2019/6/3 9:40
 */
public class CommonErrorCode {

    public static final String B_PROMOTION_TIME_ERROR = "B_PROMOTION_TIME_ERROR";

    public static final String B_PROMOTION_UPDATE_ERROR = "B_PROMOTION_UPDATE_ERROR";

    /**
     * B_PROMOTION_SUCCESS=活动计算成功 B_PROMOTION_EXPIRE_ERROR=哎呀！活动已过期，商品将按原价计算，是否继续下单购买呢！
     * B_PROMOTION_GROUP_SECKILL_MIN_NUM_ERROR=哎呀！拼团秒杀数量未达到最小起批量，请您重新调整拼团数量！
     * B_PROMOTION_GROUP_MAX_NUM_ERROR=哎呀！拼团数量已超过可拼数量，请您重新调整拼团数量！
     * B_PROMOTION_SECKILL_MAX_NUM_ERROR=哎呀！秒杀数量已超过可秒数量，请您重新调整秒杀数量！
     * B_PROMOTION_CONDITION_ERROR=哎呀！购买的商品数量或金额未达到活动条件，是否继续下单购买呢！ B_PROMOTION_CONDITION_NULL=哎呀！找不到对应的活动！
     * B_PROMOTION_GIFT_ERROR=哎呀！活动赠品不符合条件，请您重新调整赠品再下单呢！ B_PROMOTION_COUPON_ERROR=哎呀！优惠券不符合条件，请重新选择下单！
     */
    public final static String B_PROMOTION_SUCCESS = "B_PROMOTION_SUCCESS";
    public final static String B_PROMOTION_EXPIRE_ERROR = "B_PROMOTION_EXPIRE_ERROR";
    public final static String B_PROMOTION_EXPIRE_ERROR_MSG = "B_PROMOTION_EXPIRE_ERROR_MSG";
    public final static String B_PROMOTION_GROUP_SECKILL_MIN_NUM_ERROR = "B_PROMOTION_GROUP_SECKILL_MIN_NUM_ERROR";
    public final static String B_PROMOTION_GROUP_SECKILL_MIN_NUM_ERROR_MSG =
        "B_PROMOTION_GROUP_SECKILL_MIN_NUM_ERROR_MSG";
    public final static String B_PROMOTION_GROUP_MAX_NUM_ERROR = "B_PROMOTION_GROUP_MAX_NUM_ERROR";
    public final static String B_PROMOTION_GROUP_MAX_NUM_ERROR_MSG = "B_PROMOTION_GROUP_MAX_NUM_ERROR_MSG";
    public final static String B_PROMOTION_SECKILL_MAX_NUM_ERROR = "B_PROMOTION_SECKILL_MAX_NUM_ERROR";
    public final static String B_PROMOTION_SECKILL_MAX_NUM_ERROR_MSG = "B_PROMOTION_SECKILL_MAX_NUM_ERROR_MSG";
    public final static String B_PROMOTION_CONDITION_ERROR = "B_PROMOTION_CONDITION_ERROR";
    public final static String B_PROMOTION_CONDITION_NULL = "B_PROMOTION_CONDITION_NULL";
    public final static String B_PROMOTION_GIFT_ERROR = "B_PROMOTION_GIFT_ERROR";
    public final static String B_PROMOTION_COUPON_ERROR = "B_PROMOTION_COUPON_ERROR";
    public static final String B_PROMOTION_DISTRIBUTOR_SERVICE_EXCEPTION = "B_PROMOTION_DISTRIBUTOR_SERVICE_EXCEPTION";
    public static final String B_PROMOTION_DEAL_ERROR = "B_PROMOTION_DEAL_ERROR";
    public static final String B_FILE_IS_EMPTY = "B_FILE_IS_EMPTY";
    public static final String B_IMPORT_PROMOTION_NO_NULL = "B_IMPORT_PROMOTION_NO_NULL";
    public static final String B_IMPORT_PROMOTION_TYPE_ERROR = "B_IMPORT_PROMOTION_TYPE_ERROR";
    public static final String B_IMPORT_PROMOTION_NAME_NULL = "B_IMPORT_PROMOTION_NAME_NULL";
    public static final String B_IMPORT_PROMOTION_DESCRIBE_NULL = "B_IMPORT_PROMOTION_DESCRIBE_NULL";
    public static final String B_IMPORT_PROMOTION_NO_WAY_ERROR = "B_IMPORT_PROMOTION_NO_WAY_ERROR";
    public static final String B_IMPORT_PROMOTION_START_TIME_NULL = "B_IMPORT_PROMOTION_START_TIME_NULL";
    public static final String B_IMPORT_PROMOTION_END_TIME_NULL = "B_IMPORT_PROMOTION_END_TIME_NULL";
    public static final String B_IMPORT_PROMOTION_DEPARTMENT_NULL = "B_IMPORT_PROMOTION_DEPARTMENT_NULL";
    public static final String B_IMPORT_PROMOTION_TARGET_ERROR = "B_IMPORT_PROMOTION_TARGET_ERROR";
    public static final String B_IMPORT_PROMOTION_ADD_FLAG_ERROR = "B_IMPORT_PROMOTION_ADD_FLAG_ERROR";
    public static final String B_IMPORT_PROMOTION_GOODS_NO_NULL = "B_IMPORT_PROMOTION_GOODS_NO_NULL";
    public static final String B_IMPORT_PROMOTION_CONDITION_TYPE_ERROR = "B_IMPORT_PROMOTION_CONDITION_TYPE_ERROR";
    public static final String B_IMPORT_PROMOTION_TARGET_CONDITION_TYPE_ERROR =
        "B_IMPORT_PROMOTION_TARGET_CONDITION_TYPE_ERROR";
    public static final String B_IMPORT_PROMOTION_CONDITION_TYPE_NULL = "B_IMPORT_PROMOTION_CONDITION_TYPE_NULL";
    public static final String B_IMPORT_PROMOTION_ONE_BUY_COUNT_ERROR = "B_IMPORT_PROMOTION_ONE_BUY_COUNT_ERROR";
    public static final String B_IMPORT_PROMOTION_GOODS_ITEM_ERROR = "B_IMPORT_PROMOTION_GOODS_ITEM_ERROR";
    public static final String B_IMPORT_PROMOTION_GOODS_ITEM_NULL = "B_IMPORT_PROMOTION_GOODS_ITEM_NULL";
    public static final String B_IMPORT_PROMOTION_DISCOUNT_REDUCTION_ERROR =
        "B_IMPORT_PROMOTION_DISCOUNT_REDUCTION_ERROR";
    public static final String B_COUPON_USE_FLAG_ERROR = "B_COUPON_USE_FLAG_ERROR";
}
