CREATE TABLE `import_order` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '标准id',
  `erp_distributor_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'erp分销商内码',
  `distributor_id` int(10) NOT NULL COMMENT '分销商id',
  `distributor_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '分销商名称',
  `order_type_value` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '订单类型',
  `order_type_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '订单类型名称',
  `country_id` int(11) DEFAULT NULL COMMENT '国家id',
  `country_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '国家名称',
  `province_id` int(10) DEFAULT '0' COMMENT '省份id',
  `province_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '省份名称',
  `city_id` int(10) DEFAULT '0' COMMENT '市id',
  `city_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '城市名称',
  `district_id` int(10) DEFAULT '0' COMMENT '区/县id',
  `district_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '区,县名称',
  `address` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '地址',
  `zip_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '邮编',
  `user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '收货人',
  `mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '手机',
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '电话',
  `pay_way` tinyint(2) DEFAULT '0' COMMENT '支付方式',
  `delivery_type` tinyint(1) DEFAULT '0' COMMENT '送货时间类型 1.工作日，2.任意时间 3.双休 4.指定日期',
  `delivery_time` datetime DEFAULT NULL COMMENT '送货时间',
  `distribution_id` int(10) DEFAULT '0' COMMENT '配送方式id',
  `distribution_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '配送名称',
  `invoice_type` tinyint(1) DEFAULT '0' COMMENT '发票类型 1.普通 2.增值税发票',
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '备注',
  `handle_flag` tinyint(1) DEFAULT '0' COMMENT '下单状态   1:已下单  2:未下单',
  `order_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '订单id',
  `order_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT 'erp订单编号',
  `order_create_time` datetime DEFAULT NULL COMMENT '订单下单时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `count_sum` int(10) DEFAULT '0' COMMENT '货品总数量',
  `amount_sum` decimal(10,4) DEFAULT NULL COMMENT '货品总价',
  `is_invoice` tinyint(1) DEFAULT '0' COMMENT '是否开具发票   0.否，1.是',
  `operate_uid` int(10) DEFAULT '0' COMMENT '操作人ID',
  `currency_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'CNY' COMMENT '订单币种',
  `currency_rates` decimal(10,4) DEFAULT '1.0000' COMMENT '订单汇率',
  `remind` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '错误提示',
  `submit_status` tinyint(1) unsigned DEFAULT '1' COMMENT '提交状态 1.未提交，2.提交中，3.提交成功，4.提交失败',
  `order_split_flag` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '订单是否拆分 1、拆分 0、否、默认是拆',
  `manufactor` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生产商 YC.云创 LHW.联辉王',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_import_o_userId` (`distributor_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='导入订单表';

CREATE TABLE `import_order_detail` (
  `id` int(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `import_order_goods_id` int(11) unsigned NOT NULL COMMENT '导入订单详情表编号',
  `import_order_id` int(11) NOT NULL COMMENT '导入订单编号',
  `material_id` int(11) NOT NULL COMMENT '材质编号',
  `material_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '材料名称',
  `model_id` int(11) NOT NULL COMMENT '型号编号',
  `model_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '型号名称',
  `brand_id` int(11) NOT NULL COMMENT '品牌编号',
  `brand_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '品牌名称',
  `picture_id` int(11) NOT NULL COMMENT '图片编号',
  `category_id` int(11) NOT NULL DEFAULT '10010' COMMENT '类型id 10010手机壳  10020手机背膜',
  `generate_image` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '定制生成的图片PDF',
  `image` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '定制图片预览地址',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `import_order_goods_id` (`import_order_goods_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='定制订单导入定制信息详情表';

CREATE TABLE `import_order_goods` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `import_order_id` int(10) NOT NULL DEFAULT '0' COMMENT '导入订单id',
  `item_id` int(10) NOT NULL COMMENT '货品id',
  `item_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品编号',
  `item_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '货品名称',
  `goods_id` int(10) NOT NULL COMMENT '商品id',
  `goods_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '商品名称',
  `goods_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '商品编码',
  `distributor_price` decimal(10,4) DEFAULT NULL COMMENT '分销商价格',
  `promotion_amount` decimal(10,4) DEFAULT '0.0000' COMMENT '价格折扣',
  `actual_price` decimal(10,4) DEFAULT '0.0000' COMMENT '实际价格',
  `item_count` int(10) DEFAULT '0' COMMENT '货品数量',
  `actual_order_count` int(10) DEFAULT '0' COMMENT '实际下单数量',
  `item_lose_count` int(10) DEFAULT '0' COMMENT '缺货数量',
  `in_warehouse_count` int(10) DEFAULT '0' COMMENT '货品总库总数',
  `on_way_count` int(10) DEFAULT '0' COMMENT '货品在途总数',
  `goods_type` tinyint(1) DEFAULT '1' COMMENT '商品类型 1-普通  2-制定',
  `specification_value_id` int(10) DEFAULT '0' COMMENT '规格值id',
  `color_value_id` int(10) DEFAULT '0' COMMENT '颜色值id',
  `item_type` int(2) DEFAULT '1' COMMENT '货品类型 1-主货品 2-赠品',
  `grade_discount_id` int(10) unsigned DEFAULT NULL COMMENT '商品等级折扣Id',
  `rule_id` int(11) DEFAULT NULL COMMENT '促销活动规则ID',
  `order_rule_id` int(11) DEFAULT NULL COMMENT '订单促销活动规则ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_import_og_oid` (`import_order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='导入订单货品表';

CREATE TABLE `order_customer_cost` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `customer_id` int(10) unsigned NOT NULL COMMENT 'C端客户id',
  `goods_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '商品总价',
  `distribution_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '物流费用',
  `goods_promotion_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '商品促销金额',
  `order_promotion_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '订单促销金额',
  `order_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '订单总额',
  `pay_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '应付款总额',
  `paid_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '已付款金额',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `order_coupon_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '订单优惠券优惠金额',
  `out_trade_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付凭证号(注意：全平台唯一)',
  `refunded_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '已退款金额',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单总费用C端客户归属表';

CREATE TABLE `order_customer_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `customer_id` int(10) unsigned NOT NULL COMMENT 'C端客户id',
  `customer_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'C端客户用户名',
  `order_status` smallint(5) unsigned NOT NULL COMMENT '订单状态 1.待确认2.已确认 4.已取消 5.已完成',
  `pay_status` smallint(5) unsigned NOT NULL COMMENT '付款状态 1.未付款，2.部分付款 3. 已付款 4.部分退款 5.退款申请中 6.已退款',
  `pay_way` smallint(5) unsigned DEFAULT NULL COMMENT '付款方式 1.支付宝,2.微信,3.区间结算,4.线下转账,5.余额支付,6.快钱支付,7.余额+支付宝,8.余额+微信,9.余额+快钱支付',
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单备注（限制200个字符）',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `distributor_id` int(10) unsigned NOT NULL COMMENT '归属分销商id',
  `distributor_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '归属分销商用户名(登录名)',
  `company_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '归属分销商公司名',
  `shop_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '店铺编码',
  `shop_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '店铺名称',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `cancel_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '取消订单备注（限制200个字符）',
  `customer_mode` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT '分销模式： 1 平台方收款(比如：bat收款，bat收款，如果现款情况，二级以上分销商只支持现款线上支付，一级分销商可支持现款线下支付及线下银行转账), 2 自己收款(分销商自己收款)',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE,
  KEY `customer_id` (`customer_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单C端客户归属信息表';

CREATE TABLE `order_deliver_bill` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `distribution_id` int(10) unsigned DEFAULT NULL COMMENT '配送id',
  `distribution_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '配送方式编码',
  `distribution_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '配送方式名称',
  `deliver_status` smallint(5) unsigned NOT NULL COMMENT '发货状态 1待确认,2.已确认,3.已取消',
  `logistics_no` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '物流编号',
  `logistics_status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '物流状态：2-在途中,3-签收,4-问题件',
  `deliver_erp_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT 'erp出库单号',
  `deliver_stk_no` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT 'erp采购单号',
  `push` smallint(6) NOT NULL COMMENT '是否需要推送第三方,1 为是需要推送，0为不需要推送',
  `push_status` smallint(6) DEFAULT NULL COMMENT '同步给第三方成功与否: 1为同步成功，0为同步失败',
  `deliver_time` datetime DEFAULT NULL COMMENT '发货时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单发货单';

CREATE TABLE `order_deliver_bill_detail` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_deliver_bill_id` int(10) unsigned NOT NULL COMMENT '订单发货单id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `order_goods_id` int(10) unsigned NOT NULL COMMENT '订单明细id',
  `serial_number` int(10) unsigned DEFAULT NULL COMMENT '行项目序号',
  `goods_id` int(10) unsigned NOT NULL COMMENT '商品id',
  `goods_no` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '商品自定义编号',
  `goods_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品名称',
  `item_id` int(10) unsigned NOT NULL COMMENT '货品id',
  `item_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品编号',
  `bar_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '条形码',
  `item_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品名称',
  `count` int(11) DEFAULT '0' COMMENT '发货数量',
  `warehouse_id` int(10) unsigned DEFAULT NULL COMMENT '出库仓库名称',
  `warehouse_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '出库仓库名称',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_deliver_bill_id` (`order_deliver_bill_id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE,
  KEY `order_goods_id` (`order_goods_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单发货单明细表';

CREATE TABLE `order_deliver_stop_place` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `place_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地点名称',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='快递停发地点';

CREATE TABLE `order_delivery` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `distribution_id` int(10) NOT NULL COMMENT '配送方式id',
  `distribution_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '配送方式名称',
  `country_id` int(10) unsigned NOT NULL COMMENT '国家id',
  `province_id` int(10) unsigned DEFAULT NULL COMMENT '省份id',
  `city_id` int(10) unsigned DEFAULT NULL COMMENT '城市id',
  `district_id` int(10) unsigned DEFAULT NULL COMMENT '区/县id',
  `country_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '国家名称',
  `province_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '省份名称',
  `city_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '城市名称',
  `district_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '区县名称',
  `address` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '街道地址',
  `zip_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '邮政编码',
  `user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '收货人姓名',
  `mobile` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '手机',
  `phone` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '固定电话',
  `delivery_type` smallint(5) unsigned DEFAULT NULL COMMENT '送货时间类型 1.工作日，2.任意时间 3.双休 4.指定日期',
  `delivery_time` datetime DEFAULT NULL COMMENT '送货时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单送货信息表';

CREATE TABLE `order_delivery_trace` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `order_deliver_bill_id` int(10) NOT NULL DEFAULT '0' COMMENT '发货单id',
  `accept_time` datetime NOT NULL COMMENT '节点时间',
  `accept_station` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '节点轨迹描述',
  `remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_deliver_id` (`order_deliver_bill_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单发货物流轨迹表';

CREATE TABLE `order_detail_picture_local` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `order_id` int(10) NOT NULL COMMENT '订单Id',
  `order_goods_diy_id` int(10) NOT NULL COMMENT '订单详情id',
  `image_url` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '预览图',
  `generate_image_url` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生产打印图',
  `label_url` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '标签存放路径',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `root_path` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'ftp文件夹根路径',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `order_detail_index` (`order_goods_diy_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='定制订单本地图片存储关联';

CREATE TABLE `order_distributor_commission` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `distributor_ancestor_id` int(10) unsigned NOT NULL COMMENT '获得佣金分销商id',
  `distributor_descendant_id` int(10) unsigned DEFAULT NULL COMMENT '下单分销商id',
  `amount` decimal(16,4) NOT NULL DEFAULT '0.0000' COMMENT '父分销所得佣金',
  `order_ancestor_price` decimal(16,4) NOT NULL COMMENT '获得佣金分销商订单结算金额',
  `order_descendant_price` decimal(16,4) NOT NULL COMMENT '下单分销商订单结算金额',
  `commission_type` smallint(5) unsigned DEFAULT NULL COMMENT '佣金类型 1.增加，2.减少',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `distributor_ancestor_id` (`distributor_ancestor_id`) USING BTREE,
  KEY `distributor_descendant_id` (`distributor_descendant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单佣金明细分销客户归属表';

CREATE TABLE `order_distributor_cost` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `distributor_id` int(10) unsigned NOT NULL COMMENT '直属分销商id',
  `goods_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '商品总价',
  `distribution_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '物流费用',
  `goods_promotion_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '商品促销金额',
  `order_promotion_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '订单促销金额',
  `rebate_voucher_amount` decimal(16,4) DEFAULT NULL COMMENT '代金券抵扣金额',
  `deposit_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '余额支付金额',
  `pay_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '分销商归属应收款总额',
  `paid_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '已付款金额',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `out_trade_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付凭证号(注意：全平台唯一)',
  `platform_amount` decimal(16,4) DEFAULT NULL COMMENT '平台应收款总额',
  `refunded_amount` decimal(16,4) unsigned DEFAULT '0.0000' COMMENT '已退款金额',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE,
  KEY `idx_distributor_id` (`distributor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单总费用直属分销商表';

CREATE TABLE `order_distributor_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `distributor_id` int(10) unsigned NOT NULL COMMENT '直属分销商id',
  `distributor_name` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户名(登录名)',
  `distributor_contact_id` int(10) DEFAULT NULL COMMENT '下单分销商联系人id(联系人登录情况有值)',
  `distributor_contact_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下单分销商联系人名称(联系人登录情况有值)',
  `company_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '公司名',
  `distributor_ancestor_id` int(10) unsigned DEFAULT NULL COMMENT '上级分销商id',
  `distributor_ancestor_name` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '上级分销商用户名(登录名)',
  `distributor_ancestor_company_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '上级分销商公司名',
  `direct_flag` smallint(5) unsigned NOT NULL COMMENT '是否直接下单 1.是认0.否',
  `erp_flag` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '是否同步到erp 1.是 0.否',
  `tree_node` int(10) unsigned NOT NULL COMMENT '多级分销级数',
  `order_status` smallint(5) unsigned NOT NULL COMMENT '订单状态 1.待确认2.已确认 3.已拒绝 4.已取消 5.已完成',
  `pay_status` smallint(5) unsigned NOT NULL COMMENT '付款状态 1.未付款，2.部分付款 3. 已付款 4.部分退款 5.退款申请中 6.已退款',
  `pay_way` smallint(5) unsigned DEFAULT NULL COMMENT '付款方式 1.支付宝,2.微信,3.区间结算,4.线下转账,5.余额支付,6.快钱支付,7.余额+支付宝,8.余额+微信,9.余额+快钱支付',
  `distribution_mode` smallint(5) unsigned NOT NULL COMMENT '分销模式： 1 平台方收款(比如：bat收款，bat收款，如果现款情况，二级以上分销商只支持现款线上支付，一级分销商可支持现款线下支付及线下银行转账), 2 自己收款(分销商自己收款)',
  `currency_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单币种',
  `current_rates` decimal(16,4) DEFAULT NULL COMMENT '订单汇率',
  `remark` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单备注（限制200个字符）',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `cancel_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '取消订单备注（限制200个字符）',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `distributor_id` (`distributor_id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单直属分销商信息表';

CREATE TABLE `order_extend_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `order_thirdparty_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第三方客户订单编号',
  `order_erp_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'erp订单编号',
  `order_erp_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'erp订单类型（实际同步ERP类型、可能跟order_info的order_type_id不一致）',
  `order_factory_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工厂订单编号',
  `factory_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工厂',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `auto_delivery` smallint(5) unsigned DEFAULT '0' COMMENT '自动下推出库 1.是 0.否',
  `open_id` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下单者openId',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `order_id` (`order_id`) USING BTREE,
  KEY `order_erp_no` (`order_erp_no`) USING BTREE,
  KEY `order_thirdparty_no` (`order_thirdparty_no`) USING BTREE,
  KEY `factory_code` (`factory_code`) USING BTREE,
  KEY `order_factory_no` (`order_factory_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单扩展数据表';

CREATE TABLE `order_goods` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `serial_number` int(10) unsigned DEFAULT NULL COMMENT '行项目序号',
  `goods_id` int(10) unsigned NOT NULL COMMENT '商品(SPU)id',
  `goods_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品名称',
  `goods_no` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品编号',
  `item_id` int(10) unsigned NOT NULL COMMENT '货品(SKU)id',
  `item_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品编号',
  `bar_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '条形码',
  `item_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '货品名称',
  `goods_type` smallint(4) NOT NULL DEFAULT '1' COMMENT '商品类型 1-普通 2-定制',
  `diy_type` smallint(4) DEFAULT '1' COMMENT '定制类型 0、标准定制 1、DIY定制',
  `specs_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '规格值名称',
  `color_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '颜色值名称',
  `weight` decimal(10,3) DEFAULT NULL COMMENT '重量（克）',
  `length` decimal(10,3) DEFAULT NULL COMMENT '长度,mm',
  `width` decimal(10,3) DEFAULT NULL COMMENT '宽(mm)',
  `height` decimal(10,3) DEFAULT NULL COMMENT '高（mm）',
  `warehouse_id` int(10) unsigned DEFAULT NULL COMMENT '锁库仓库id',
  `item_count` int(10) unsigned NOT NULL COMMENT '货品总数量',
  `item_in_count` int(10) unsigned DEFAULT '0' COMMENT '在库货品数量',
  `item_vmi_count` int(10) unsigned DEFAULT '0' COMMENT 'vmi货品数量',
  `item_on_way_count` int(10) unsigned DEFAULT '0' COMMENT '在途货品数量',
  `deliver_count` int(10) unsigned DEFAULT '0' COMMENT '已发货数量',
  `un_deliver_count` int(10) unsigned DEFAULT '0' COMMENT '未发货数量',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `image_url` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品图片地址',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单明细表';

CREATE TABLE `order_goods_customer_cost` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_goods_id` int(10) unsigned NOT NULL COMMENT '订单明细id',
  `customer_id` int(10) unsigned NOT NULL COMMENT 'C端客户id',
  `item_type` smallint(6) DEFAULT NULL COMMENT '是否赠品 1 非赠品 2 赠品',
  `sale_price` decimal(16,4) NOT NULL COMMENT '单价',
  `actual_price` decimal(16,4) NOT NULL COMMENT '实际单价',
  `goods_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '商品促销活动id(活动条件id)',
  `order_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '订单促销活动id(活动条件id)',
  `spell_group_id` int(11) DEFAULT NULL COMMENT '拼团秒杀活动id',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `coupon_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '优惠券码(多个中间用逗号隔开)',
  `coupon_method` smallint(5) unsigned DEFAULT NULL COMMENT '优惠形式，1满减  2满折 3兑换',
  `delivery_fee_flag` smallint(5) unsigned DEFAULT NULL COMMENT '是否收取快递费 0否 1是',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `customer_id` (`customer_id`) USING BTREE,
  KEY `order_goods_id` (`order_goods_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单明细费用分销商归属表';

CREATE TABLE `order_goods_distributor_cost` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_goods_id` int(10) unsigned NOT NULL COMMENT '订单明细id',
  `distributor_id` int(10) unsigned NOT NULL COMMENT '直属分销商id',
  `item_type` smallint(6) DEFAULT NULL COMMENT '是否赠品 1 非赠品 2 赠品',
  `sale_price` decimal(16,4) NOT NULL COMMENT '分销商归属分销商会员单价',
  `actual_price` decimal(16,4) NOT NULL COMMENT '分销商归属实际结算单价',
  `rebate_voucher_amount` decimal(16,4) DEFAULT NULL COMMENT '商品单价抵扣 金额',
  `goods_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '商品促销活动Id(活动条件id)',
  `order_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '订单促销活动Id(活动条件id)',
  `spell_group_id` int(11) DEFAULT NULL COMMENT '拼团秒杀活动id',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `platform_price` decimal(16,4) DEFAULT NULL COMMENT '平台收款单价',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `distributor_id` (`distributor_id`) USING BTREE,
  KEY `order_goods_id` (`order_goods_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单明细费用直属分销商表';

CREATE TABLE `order_goods_diy` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_goods_id` int(10) unsigned NOT NULL COMMENT '订单明细id',
  `category_id` int(10) unsigned NOT NULL COMMENT '产品类型id',
  `category_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '产品类型名称',
  `material_id` int(10) unsigned NOT NULL COMMENT '材质id',
  `material_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '材料名称',
  `model_id` int(10) unsigned NOT NULL COMMENT '型号id',
  `model_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '型号名称',
  `brand_id` int(10) unsigned NOT NULL COMMENT '品牌id',
  `brand_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '品牌名称',
  `picture_id` int(10) unsigned NOT NULL COMMENT '图片id(网络图为0)',
  `label_id` int(10) unsigned DEFAULT NULL COMMENT '标签id',
  `label_url` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '标签存放路径',
  `generate_image` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '生产图URL地址',
  `preview_image` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '预览图URL地址',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `manufactors` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '生产商 YC云创 MK麦客 LHW联辉王',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `category_id` (`category_id`) USING BTREE,
  KEY `material_id` (`material_id`) USING BTREE,
  KEY `model_id` (`model_id`) USING BTREE,
  KEY `brand_id` (`brand_id`) USING BTREE,
  KEY `picture_id` (`picture_id`) USING BTREE,
  KEY `order_goods_id` (`order_goods_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='定制商品信息扩展表';

CREATE TABLE `order_goods_exchange_code` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_goods_id` int(10) unsigned NOT NULL COMMENT '订单明细id',
  `exchange_id` int(10) unsigned NOT NULL COMMENT '兑换卡活动id',
  `secret_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '暗码',
  `mail_setting` smallint(5) unsigned DEFAULT NULL COMMENT '快递收费模式 1、包邮（普通卡）2、收运费（赠卡）3、收运费（普通卡加收用户运费）',
  `mail_fee` decimal(16,3) unsigned DEFAULT '0.000' COMMENT '邮费',
  `exchange_order_id` int(10) unsigned DEFAULT NULL COMMENT '兑换卡归属订单号',
  `distributor_id` int(10) unsigned DEFAULT NULL COMMENT '发卡分销商id',
  `distributor_company_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发卡分销商公司名',
  `sales_id` int(10) unsigned DEFAULT NULL COMMENT '业务员id',
  `sales_name` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '业务员姓名',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `exchange_order_goods_id` int(10) unsigned DEFAULT NULL COMMENT '兑换卡归属订单明细号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_goods_id` (`order_goods_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单明细兑换卡关联信息';

CREATE TABLE `order_goods_stock` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `order_goods_id` int(10) unsigned NOT NULL COMMENT '订单明细id',
  `goods_id` int(10) unsigned NOT NULL COMMENT '商品id',
  `item_id` int(10) unsigned NOT NULL COMMENT '货品id',
  `stock_id` int(10) unsigned DEFAULT NULL COMMENT '库存明细id(包括在途、在库和vmi)',
  `warehouse_id` int(10) unsigned DEFAULT NULL COMMENT '仓库id',
  `lock_num` int(11) NOT NULL COMMENT '订单锁定数量',
  `lock_type` smallint(6) NOT NULL COMMENT '锁定类型 1.在库 2.在途 3.vmi',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE,
  KEY `order_goods_id` (`order_goods_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单商品库存锁定记录表';

CREATE TABLE `order_goods_third_code` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_goods_id` int(11) unsigned NOT NULL COMMENT '订单明细id',
  `order_id` int(11) unsigned NOT NULL COMMENT '订单id',
  `code` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '兑换码',
  `write_off_flag` smallint(5) unsigned NOT NULL COMMENT '是否已核销 0否 1是',
  `distributor_id` int(11) unsigned NOT NULL COMMENT '分销商id',
  `platform` varchar(20) NOT NULL COMMENT '平台绑定编码(分销商平台编码)',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_code` (`code`) USING BTREE,
  KEY `order_goods_id` (`order_goods_id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='第三方兑换码';

CREATE TABLE `order_info` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单编号',
  `deliver_status` smallint(5) unsigned NOT NULL COMMENT '发货状态 1.未发货2.出库中 3.部分发货 4.已发货 ',
  `deliver_time` datetime DEFAULT NULL COMMENT '发货时间(发货状态为部分发货或已发货时有值)',
  `order_type_id` int(10) unsigned NOT NULL COMMENT '订单类型id',
  `stock_type` smallint(5) unsigned NOT NULL COMMENT '库存类型：1在库 2在途 3预售(mto)  4 在途+在库 5、委外',
  `sales_id` int(10) unsigned NOT NULL COMMENT '业务员id',
  `sales_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务员姓名',
  `coordinator_id` int(10) unsigned DEFAULT NULL COMMENT '商务员id',
  `coordinator_name` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商务员姓名',
  `invoice_flag` smallint(5) unsigned NOT NULL COMMENT '是否开具发票 0.否，1.是',
  `order_source` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单来源：分销平台编码',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `language` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '业务语言：zh 中文 en 英文 ',
  `organization_id` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '组织id',
  `organization_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '组织名',
  `organization_erp` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'ERP_组织代码',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `order_no` (`order_no`) USING BTREE,
  KEY `order_source` (`order_source`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单基本信息表';

CREATE TABLE `order_invoice` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单ID',
  `invoice_type` smallint(5) unsigned NOT NULL COMMENT '发票类型 1.普通 2.增值税发票',
  `invoice_title_type` smallint(5) unsigned NOT NULL COMMENT '发票抬头 1.个人 2.单位',
  `taxpayer_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '纳税人识别号(发票抬头为2时必填)',
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '发票名称 (个人姓名或单位名称)',
  `register_address` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '公司注册地址',
  `register_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '公司注册电话',
  `bank_account_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '银行账户名',
  `bank_account` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '银行账号',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单发票信息(一般是收款账户主体开票)';

CREATE TABLE `order_type` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单类型名称',
  `erp_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'erp订单类型',
  `warehouse_id` int(10) unsigned DEFAULT NULL COMMENT '默认仓库id',
  `special_flag` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT '特殊类型, 1 普通,2 mto,3 现款,4 定制,5 直运',
  `description` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单类型描述',
  `editable` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT '是否可编辑：1-可编辑 0-不可编辑',
  `open_flag` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT '是否启用, 0为停用，1为启用',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单类型表';

CREATE TABLE `shopping_cart_customer` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `customer_id` int(10) unsigned NOT NULL COMMENT 'C端客户id',
  `distributor_id` int(10) unsigned NOT NULL COMMENT 'C端客户归属分销商id',
  `goods_id` int(10) unsigned NOT NULL COMMENT '商品(SPU)id',
  `goods_no` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '商品编号',
  `goods_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品名称',
  `item_id` int(10) unsigned NOT NULL COMMENT '货品(SKU)id',
  `item_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品编号',
  `item_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品名称',
  `goods_type` smallint(6) DEFAULT '1' COMMENT '商品类型 1-普通 2-定制',
  `diy_type` smallint(6) DEFAULT '1' COMMENT '定制类型 0-标准定制 1-DIY定制',
  `goods_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '商品促销活动Id(活动规则id)',
  `order_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '订单促销活动Id(活动规则id)',
  `group_seckill_id` int(10) unsigned DEFAULT NULL COMMENT '拼团秒杀活动id',
  `item_count` int(10) unsigned NOT NULL COMMENT '货品总数量',
  `open_flag` smallint(6) NOT NULL DEFAULT '1' COMMENT '商品是否有效 1、有效 0、无效',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `item_type` smallint(6) DEFAULT NULL COMMENT '是否赠品 1 非赠品 2 赠品',
  `specs_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '规格值名称',
  `color_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '颜色值名称',
  `language` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '业务语言：zh 中文 en 英文 ',
  `image_url` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品图片地址',
  `weight` decimal(16,3) DEFAULT '0.000' COMMENT '重量，克',
  `length` decimal(16,3) DEFAULT '0.000' COMMENT '长度',
  `width` decimal(16,3) DEFAULT '0.000' COMMENT '宽',
  `height` decimal(16,3) DEFAULT '0.000' COMMENT '高',
  `bar_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '条形码',
  `unit` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '数量单位名称',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `customer_id` (`customer_id`) USING BTREE,
  KEY `distributor_id` (`distributor_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='分销客户购物车表';

CREATE TABLE `shopping_cart_distributor` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `distributor_id` int(10) unsigned NOT NULL COMMENT '分销商id',
  `goods_id` int(10) unsigned NOT NULL COMMENT '商品(SPU)id',
  `goods_no` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '商品编号',
  `goods_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品名称',
  `item_id` int(10) unsigned NOT NULL COMMENT '货品(SKU)id',
  `item_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品编号',
  `item_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '货品名称',
  `goods_type` smallint(6) DEFAULT '1' COMMENT '商品类型 1-普通 2-定制',
  `diy_type` smallint(6) DEFAULT '1' COMMENT '定制类型 0-标准定制 1-DIY定制',
  `goods_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '商品促销活动Id(活动规则id)',
  `order_promotion_id` int(10) unsigned DEFAULT NULL COMMENT '订单促销活动Id(活动规则id)',
  `group_seckill_id` int(10) unsigned DEFAULT NULL COMMENT '拼团秒杀活动id',
  `open_flag` smallint(6) NOT NULL DEFAULT '1' COMMENT '商品是否有效 1、有效 0、无效',
  `item_count` int(10) unsigned NOT NULL COMMENT '货品总数量',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `item_type` smallint(6) DEFAULT NULL COMMENT '是否赠品 1 非赠品 2 赠品',
  `color_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '颜色值名称',
  `specs_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '规格值名称',
  `language` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '业务语言：zh 中文 en 英文 ',
  `image_url` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品图片地址',
  `weight` decimal(16,3) DEFAULT '0.000' COMMENT '重量，克',
  `length` decimal(16,3) DEFAULT '0.000' COMMENT '长度',
  `width` decimal(16,3) DEFAULT '0.000' COMMENT '宽',
  `height` decimal(16,3) DEFAULT '0.000' COMMENT '高',
  `bar_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '条形码',
  `unit` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '数量单位名称',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `distributor_id` (`distributor_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='分销客户购物车表';

CREATE TABLE `shopping_cart_diy_customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `shopping_cart_customer_id` int(10) unsigned NOT NULL COMMENT 'C端客户购物车id',
  `category_id` int(10) unsigned NOT NULL COMMENT '产品类型id',
  `category_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '产品类型名称',
  `material_id` int(10) unsigned NOT NULL COMMENT '材质id',
  `material_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '材质名称',
  `model_id` int(10) unsigned NOT NULL COMMENT '型号id',
  `model_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '型号名称',
  `brand_id` int(10) unsigned NOT NULL COMMENT '品牌id',
  `brand_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '品牌名称',
  `picture_id` int(10) unsigned NOT NULL COMMENT '图片id(网络图为0)',
  `picture_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '图片名称',
  `generate_image` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '生产图URL地址',
  `preview_image` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '预览图URL地址',
  `open_flag` smallint(6) NOT NULL DEFAULT '1' COMMENT '定制是否有效 1、有效 0、无效',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `manufactors` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '生产商 YC云创 MK麦客 LHW联辉王',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `shopping_cart_customer_id` (`shopping_cart_customer_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='分销客户购物车定制信息表';

CREATE TABLE `shopping_cart_diy_distributor` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `shopping_cart_distributor_id` int(10) unsigned NOT NULL COMMENT '分销客户购物车id',
  `category_id` int(10) unsigned NOT NULL COMMENT '产品类型id',
  `category_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '产品类型名称',
  `material_id` int(10) unsigned NOT NULL COMMENT '材质id',
  `material_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '材质名称',
  `model_id` int(10) unsigned NOT NULL COMMENT '型号id',
  `model_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '型号名称',
  `brand_id` int(10) unsigned NOT NULL COMMENT '品牌id',
  `brand_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '品牌名称',
  `picture_id` int(10) unsigned NOT NULL COMMENT '图片id(网络图为0)',
  `picture_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '图片名称',
  `generate_image` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '生产图URL地址',
  `preview_image` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '预览图URL地址',
  `open_flag` smallint(6) NOT NULL DEFAULT '1' COMMENT '定制是否有效 1、有效 0、无效',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `manufactors` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '生产商 YC云创 MK麦客 LHW联辉王',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `shopping_cart_distributor_id` (`shopping_cart_distributor_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='分销客户购物车定制信息表';

