package com.bat.distributor.service.customer.executor;

public class ErrorCode {
    public static final String B_DISTRIBUTOR_CUSTOMER_NULL = "B_DISTRIBUTOR_CUSTOMER_NULL";
    public static final String B_DISTRIBUTOR_CUSTOMER_PASSWORD_NULL = "B_DISTRIBUTOR_CUSTOMER_PASSWORD_NULL";
    public static final String B_DISTRIBUTOR_CUSTOMER_PASSWORD_ERROR = "B_DISTRIBUTOR_CUSTOMER_PASSWORD_ERROR";

    public static final String B_DISTRIBUTOR_CUSTOMER_STATUS = "B_DISTRIBUTOR_CUSTOMER_STATUS";
    public static final String B_DISTRIBUTOR_CUSTOMER_CHANGE_PASSWORD_NULL =
        "B_DISTRIBUTOR_CUSTOMER_CHANGE_PASSWORD_NULL";
    public static final String B_DISTRIBUTOR_CUSTOMER_PHONE_ERROR = "B_DISTRIBUTOR_CUSTOMER_PHONE_ERROR";
    public static final String B_DISTRIBUTOR_WX_PLATFORM_NULL = "B_DISTRIBUTOR_WX_PLATFORM_NULL";
    public static final String B_DISTRIBUTOR_DY_PLATFORM_NULL = "B_DISTRIBUTOR_DY_PLATFORM_NULL";
    public static final String B_DISTRIBUTOR_ALIPAY_PLATFORM_NULL = "B_DISTRIBUTOR_ALIPAY_PLATFORM_NULL";
    public static final String B_DISTRIBUTOR_WX_PLATFORM_ERROR = "B_DISTRIBUTOR_WX_PLATFORM_ERROR";
}
